### ISSUE TITLE
modarin256: a new 256-color skin for mc

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#2737]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/2737 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `bloody` (bloody@….in-berlin.de) |
> | **Mentions** | `onlyjob@….fsf.org` (@onlyjob) |
> | **Keywords** | `256`, `color`, `skins` |

<p>
As i wrote in a mail in the devel list, mc still lacks a few more<br />
256-color skins. I've attached a new one, created in 8 different<br />
setups for solid/transparent backgrounds, regular/root users, and<br />
even four 16-color fallback skins in case 256colors is not available.<br />
</p>
<p>
Detailed info is in the file comment inside the skin files.<br />
</p>
<p>
Maybe you like to add the skin(s) to mc (at least the 256-color<br />
versions, but the 16-bit fallback skins would actually make<br />
sense..)<br />
</p>
<p>
Furthermore:<br />
</p>
<p>
Maybe you want to add a bit documentation about using 256-color<br />
skins with mc in general, like:<br />
</p>
<h5 id="beginaddtomcdocs">begin add to mc docs</h5>
<p>
With most of the common desktop terminals, enabling 256-color mode is easily<br />
done just by setting $TERM to "xterm-256color". Ubuntu users: make sure that<br />
the ncurses-term package is installed.<br />
</p>
<p>
Hint: if you decide to use a 256-color skin as default skin in your mc ini,<br />
note that if mc is started in a 16-color terminal, mc will pop up a warning<br />
saying that 256 color skins can't be used and that mc will switch to the<br />
"default" skin. To get a skin of your choice loaded instead of mc's default<br />
skin, you might consider the following solution:<br />
</p>
<p>
Create an alias for mc in your ~/.bashrc, like:<br />
</p>
<blockquote>
<p>
if [ $TERM = "linux" ]; then<br />
</p>
<blockquote>
<p>
if [ $USER = "root" ]; then<br />
</p>
<blockquote>
<p>
myMCFallbackSkin="modarcon16root-defbg"<br />
</p>
</blockquote>
<p>
else<br />
</p>
<blockquote>
<p>
myMCFallbackSkin="modarcon16-defbg"<br />
</p>
</blockquote>
<p>
fi<br />
alias mc="mc --skin $myMCFallbackSkin"<br />
alias mcedit="mcedit --skin $myMCFallbackSkin"<br />
alias mcview="mcview --skin $myMCFallbackSkin"<br />
alias mcdiff="mcdiff --skin $myMCFallbackSkin"<br />
</p>
</blockquote>
<p>
fi<br />
</p>
</blockquote>
<p>
Linux users: to use 256-color skins in the linux console, run fbterm,<br />
set $TERM to "fbterm" and then run mc within fbterm.<br />
You need to specify a gfx mode in your bootloader for the kernel to use a<br />
framebuffer console instead of the default text mode.<br />
</p>
<h5 id="endaddtomcdocs">end add to mc docs</h5>
<p>
Cheers,<br />
</p>
<p>
Oliver.<br />
</p>

> [!NOTE]
> Original attachments:
>
> * [modarin-1.0.tar.gz](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/2737/modarin-1.0.tar.gz) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/2737/modarin-1.0.tar.gz)) by `bloody` (bloody@….in-berlin.de) on <span title="2012-02-28T12:05:42+00:00">`Feb 28, 2012 at 12:05 UTC`</span>
> * [modarin-1.1.tar.gz](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/2737/modarin-1.1.tar.gz) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/2737/modarin-1.1.tar.gz)) by `bloody` (bloody@….in-berlin.de) on <span title="2012-02-28T14:21:30+00:00">`Feb 28, 2012 at 14:21 UTC`</span>
> * [modarin-1.2.tar.gz](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/2737/modarin-1.2.tar.gz) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/2737/modarin-1.2.tar.gz)) by `bloody` (bloody@….in-berlin.de) on <span title="2012-03-02T17:19:55+00:00">`Mar 2, 2012 at 17:19 UTC`</span>

**Comment by ohbob** [comment]
mandarin(modarin256) skins are on fire! Thanks
