### ISSUE TITLE
Add RSA key based authentication for SFTP

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#3238]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/3238 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `kslychan` (krzysztof.slychan@….pl) |
> | **Mentions** | `richlv@….net`, `dnh@….org`, `mooffie@….com` (@mooffie) |
> | **Keywords** | `ssh`, `sftp`, `rsa`, `key` |

<p>
mc asks me for user's password on a SSH server whenever I connect to it via SFTP, even though the client's public RSA key is authorized for that user account on the server and I can connect to it via openssh-client without giving password.<br />
</p>
<p>
Test case:<br />
</p>
<ol><li>on machine "foo", install mc, openssh-client
</li><li>on machine "foo", use ssh-keygen to generate a pair of RSA keys
</li><li>on machine "bar", install openssh-server
</li><li>on machine "bar", add the contents of machine A's ~/.ssh/id_rsa.pub to the ~/.ssh/authorized_keys file
</li><li>verify that you can connect from foo to bar without being asked for password: ssh bar (or: ssh differentusername@bar)
</li><li>if 5., then run mc, connect via SFTP, enter hostname
</li><li>you're asked for password
</li></ol><p>
Consider using key-based SSH authentication.<br />
</p>

**Comment by tuffnatty** [comment]
The issue seems to be initially about the inability to SFTP with the default key, without specifying it in `~/.ssh/config`. This has never been fixed.
