### ISSUE TITLE
"Output lines" has no effect

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#3655]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/3655 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `andrew_b` (@aborodin) |

<p>
The "Output lines" option in "Layout" dialog has no effect.<br />
</p>
<p>
Run mc in native Linux console.<br />
Run menu -&gt; "Options" -&gt; "Layout..." command.<br />
Press the "+" button at "Console output" -&gt; "Output lines:&#34; some times to increase the value. Press &#34;OK" button.<br />
</p>
<p>
There is no effect.<br />
</p>
<p>
If you open the "Layout" dialog again, you can see that value of output lines is 0.<br />
</p>
<p>
This bug was introduced in [a8101d84037887121e5f1c32759a014af6aeaa6d] (ticket #3060).<br />
</p>

**Comment by EugenKonkov-Veem** [comment]
Can not change number of lines for output:

<img width="1224" height="636" alt="Image" src="https://github.com/user-attachments/assets/7809e443-7445-4ff2-abc9-1582d829260b" />

I want to lines here:

<img width="1022" height="304" alt="Image" src="https://github.com/user-attachments/assets/fe0694cf-57a5-4fa8-9a03-1222f60c79bb" />

**Comment by zyv** [comment]
You are not on Linux console.

**Comment by EugenKonkov-Veem** [comment]
@zyv Yes, I am on Mac iTerm2

**Comment by zyv** [comment]
I know. This function only works on Linux console.
