### ISSUE TITLE
ftp: fail to retrieve password from .netrc when user is in URL

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#3869]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/3869 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `cri` (cri@….org) |

<p>
I have a proper entry in <tt>~/.netrc</tt> for USERNAME, PASSWORD and HOST.<br />
</p>
<p>
If I try to access the URL <a class="ext-link" href="ftp://HOST/PATH">ftp://HOST/PATH</a>, mc correctly retrieves USERNAME and PASSWORD from <tt>.netrc</tt> and I can log into the FTP host.<br />
</p>
<p>
If I try to access the URL <a class="ext-link" href="ftp://USERNAME@HOST/PATH">ftp://USERNAME@HOST/PATH</a>, mc displays a popup window, asking for the password. Shouldn't it retrieve the password from <tt>.netrc</tt>?<br />
</p>
<p>
I had a look at <a href="https://midnight-commander.org/browser/src/vfs/ftpfs/ftpfs.c#L371">https://midnight-commander.org/browser/src/vfs/ftpfs/ftpfs.c#L371</a><br />
</p>
<p>
shouldn't it be <br />
</p>

```
...`&& path_element->password == NULL`
```
<p>
instead of<br />
</p>

```
...`&& path_element->password != NULL`
```
<p>
?<br />
</p>
<p>
Or am I missing something?<br />
</p>

**Comment by Vrihub** [comment]
The `ftp://user@host` case is still buggy in master: mc keeps asking for a password even if there's one in .netrc. See #4831 for a proposed fix.

(the `ftp://host` case works OK: both user and password are retrieved correctly)
