### ISSUE TITLE
Can't re-define keys for files selecting/unselecting

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#3947]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/3947 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `evengerova` (helen@….ru) |
> | **Keywords** | `keymap`, `select`, `unselect` |

<p>
When I use any "+" or any "-" mc shows select/unselect menu.<br />
I want to re-define the keys since at the moment I can't specify options using "-" in the command I type in the bottom of the page (unselect menu appears). <br />
I tried to re-define in $HOME/.config/mc/mc.keymap and in /etc/mc/mc.keymap (tried to specify ctrl-plus and ctrl-minus), but looks like the setting is ignored.<br />
</p>
<p>
LC_MESSAGES=C mc -V<br />
GNU Midnight Commander 4.8.19<br />
Built with GLib 2.53.4<br />
Using the S-Lang library with terminfo database<br />
With builtin Editor<br />
With subshell support as default<br />
With support for background operations<br />
With mouse support on xterm and Linux console<br />
With internationalization support<br />
With multiple codepages support<br />
Virtual File Systems: cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, fish, smbfs<br />
Data types: char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;<br />
[helen@aule ~]$ LC_MESSAGES=C mc -F<br />
Home directory: /home/helen<br />
Profile root directory: /home/helen<br />
</p>
<p>
[System data]<br />
</p>
<blockquote>
<p>
Config directory: /etc/mc/<br />
Data directory:   /usr/share/mc/<br />
File extension handlers: /usr/libexec/mc/ext.d/<br />
VFS plugins and scripts: /usr/libexec/mc/<br />
</p>
<blockquote>
<p>
extfs.d:        /usr/libexec/mc/extfs.d/<br />
fish:           /usr/libexec/mc/fish/<br />
</p>
</blockquote>
</blockquote>
<p>
[User data]<br />
</p>
<blockquote>
<p>
Config directory: /home/helen/.config/mc/<br />
Data directory:   /home/helen/.local/share/mc/<br />
</p>
<blockquote>
<p>
skins:          /home/helen/.local/share/mc/skins/<br />
extfs.d:        /home/helen/.local/share/mc/extfs.d/<br />
fish:           /home/helen/.local/share/mc/fish/<br />
mcedit macros:  /home/helen/.local/share/mc/mc.macros<br />
mcedit external macros: /home/helen/.local/share/mc/mcedit/macros.d/macro.*<br />
</p>
</blockquote>
<p>
Cache directory:  /home/helen/.cache/mc/<br />
</p>
</blockquote>
<p>
[helen@aule ~]$ mc --configure-options<br />
</p>
<blockquote>
<p>
'--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wno-strict-aliasing' '--disable-rpath' '--enable-aspell' '--enable-charset' '--enable-largefile' '--enable-vfs-cpio' '--enable-vfs-extfs' '--enable-vfs-fish' '--enable-vfs-ftp' '--enable-vfs-sfs' '--enable-vfs-sftp' '--enable-vfs-smb' '--enable-vfs-tar' '--with-x' '--with-gpm-mouse' '--with-screen=slang' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'<br />
</p>
</blockquote>

**Comment by GfEW** [comment]
> There are two options in the ini file:
> 
> **alternate_plus_minus** (not documented in the man page):

> **only_leading_plus_minus**:

Just for the record, for everyone else stumbling upon this:

The lack of documentation has been resolved - as of mc v4.8.33, `alternate_plus_minus` and `only_leading_plus_minus` are covered by the man page.
