### ISSUE TITLE
Some new extensions for filehighlight.ini

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#4015]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4015 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `cri` (cri@….org) |

<p>
Some suggestions for new extensions to be added to filehighlight.ini<br />
</p>
<p>
[archive]: <tt>apk</tt> (android packages), <tt>deb</tt> (debian packages)<br />
</p>
<p>
[media]: <tt>ts</tt> (MPEG-TS streams)<br />
</p>
<p>
[temp]: <tt>part</tt> (partial files, e.g. used by many download managers)<br />
</p>

**Comment by zyv** [comment]
Relates to #4711.
