### ISSUE TITLE
tcsh "The Commander can't change to the directory" error

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#4120]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4120 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `congest` (hydrogenbuilding@….com) |

<p>
How to reproduce:<br />
</p>
<p>
Use tsch as your shell.<br />
ctrl-o<br />
ctrl-c<br />
ctrl-o<br />
</p>
<p>
mc gives the error:<br />
</p>

```
The Commander can't change to the directory that the subshell claims you are in. Perhaps you have deleted your working directory, or given yourself extra permissions with the "su" command?
```
<p>
I'm pretty sure this is caused by a bug in tsch. I attached a patch with a really simple workaround that makes the problem go away.<br />
</p>

> [!NOTE]
> Original attachments:
>
> * [tcsh_fix.patch](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/4120/tcsh_fix.patch) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/4120/tcsh_fix.patch)) by `congest` (hydrogenbuilding@….com) on <span title="2020-10-01T23:27:29+00:00">`Oct 1, 2020 at 23:27 UTC`</span>

**Comment by egmontkob** [comment]
strace'ing tcsh reveals that:

- with the `echo -n` trick, it first prints `\e[K` (the escape sequence to clear to the end of the line) to stdout, followed by cwd to the fifo;

- without that trick, it prints `\e[K` followed by cwd (in a single `write()` call) to the fifo.

Indeed clearly a tcsh bug.

**Comment by zyv** [comment]
But it's working now, right?

**Comment by egmontkob** [comment]
Yes, with the workaround committed 5 years ago, it seems to work reliably.

**Comment by egmontkob** [comment]
I just totally didn't understand that `echo -n` and _wanted_ to remove it, but (I verified) it would have reintroduced the bug.

**Comment by egmontkob** [comment]
Conclusion for all of us: If the code really _looks_ stupid then it needs comments :)
