### ISSUE TITLE
Opening .PAK and .ARC archives with Midnight Commander

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#4130]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4130 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `Trux` (david.vantyghem@….net) |
> | **Keywords** | `pak`, `arc`, `unar` |

<p>
1) Midnight Commander doesn't open .ARC archives.<br />
After installing arc package, I can extract files from .ARC archive with Midnight Commander. <br />
Could you please add a package dependency between mc and arc packages ?<br />
</p>
<p>
2) Midnight Commander doesn't open .PAK archives.<br />
After installing unar (not unrar) package, I can extract files from .PAK archive with the unar command but not with Midnight Commander.<br />
</p>
<p>
Could you please add in Midnight Commander a call to unar command and a package dependency between mc and unar packages ?<br />
</p>
<p>
$ mc --version<br />
GNU Midnight Commander 4.8.24<br />
Compilé avec GLib 2.63.3<br />
Utilise la bibliothèque S-Lang avec la base de données terminfo<br />
With builtin Editor and Aspell support<br />
Avec support des sous-shells par défaut<br />
Avec support des opérations en tâche de fond<br />
Avec support de la souris pour xterm et la console Linux<br />
Avec support des événements X11<br />
Avec support de l'internationalisation<br />
Avec support de plusieurs codepages<br />
Systèmes des fichiers virtuels : cpiofs, tarfs, sfs, extfs, ext2undelfs, ftpfs, sftpfs, fish<br />
Types de données : char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;<br />
</p>

> [!NOTE]
> Original attachments:
>
> * [EGACHESS.ARC](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/4130/EGACHESS.ARC) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/4130/EGACHESS.ARC)) by `Trux` (david.vantyghem@….net) on <span title="2020-10-11T11:30:25+00:00">`Oct 11, 2020 at 11:30 UTC`</span>
> * [MM34.PAK](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/4130/MM34.PAK) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/4130/MM34.PAK)) by `Trux` (david.vantyghem@….net) on <span title="2020-10-11T11:30:36+00:00">`Oct 11, 2020 at 11:30 UTC`</span>
> * [4130_PAK_support.patch](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/4130/4130_PAK_support.patch) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/4130/4130_PAK_support.patch)) by `angel_il` (@ilia-maslakov) on <span title="2020-10-12T22:29:52+00:00">`Oct 12, 2020 at 22:29 UTC`</span>

**Comment by InfoLibre** [comment]
Tested in Linux Mint Cinnamon 22.3, it works perfectly after installing arc and unar packages.
