### ISSUE TITLE
mc does not threat TERM=screen.xterm-256color as 256 colored terminal

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#4148]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4148 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `Hubbitus` (@Hubbitus) |

<p>
I use GNU screen and run mc inside them.<br />
</p>

```
$ echo $TERM
$ screen.xterm-256color
$ mc --skin=modarin256root-defbg

┌────────────────────────────── Error ──────────────────────────────┐
│                                                                   │
│ Unable to use 'modarin256root-defbg' skin with 256 colors support │
│                    on non-256 colors terminal.                    │
│                   Default skin has been loaded                    │
│                                                                   │
└───────────────────────────────────────────────────────────────────┘
```
<p>
                                                                      <br />
Run correctly with:<br />
</p>

```
TERM=xterm-256color mc --skin=modarin256root-defbg
```
<p>
Fedora Linux 33<br />
</p>
<p>
# rpm -q mc screen<br />
mc-4.8.25-3.fc33.x86_64<br />
screen-4.8.0-3.fc33.x86_64<br />
</p>

**Comment by zenczykowski** [comment]
Ran into this - nightmare to debug...

AFAICT, TERMCAP doesn't support >8 fg/bg colors (though it does support bold).

Screen sets TERMCAP and I can't find a way to prevent that.

'mc' uses S-Lang (at least on my system) which prefers TERMCAP to TERM (terminfo).
However it ignores TERMCAP if TERM starts with xterm.

Fix appears to be to simply add
  export -n TERMCAP
  unset TERMCAP
in ~/.bashrc
(or maybe ~/.bash_profile or whatever appropriate place for your shell)

You can also create a function for mc/mcedit to run with TERMCAP=  (if you need TERMCAP for other reasons)

unalias mc

unalias mcedit

mc() {
  TERMCAP= . /usr/lib/mc/mc-wrapper.sh "$@";
}

mcedit() {
  TERMCAP= /usr/bin/mcedit "$@";
}
