### ISSUE TITLE
Not all files shown on drvfs volume in WSL2 if getdents64 returns an offset

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#4454]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4454 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `pasiasty` (@cezary-zemis) |

<h2 id="Conditions">Conditions</h2>
<p>
I have observed the issue <strong>only</strong> on <strong>drvfs</strong> volumes in <strong>WSL2</strong> - Ubuntu. <br />
</p>
<h2 id="Description">Description</h2>
<p>
If a directory contains more that a few hundred of files, not all are shown. Using strace I have determined that output of first getdents64 is ignored. <br />
</p>
<h2 id="MCversion">MC version</h2>
<p>
GNU Midnight Commander 4.8.27<br />
Built with GLib 2.68.4<br />
Built with S-Lang 2.3.2 with terminfo database<br />
With builtin Editor and Aspell support<br />
With subshell support as default<br />
With support for background operations<br />
With mouse support on xterm and Linux console<br />
With support for X11 events<br />
With internationalization support<br />
With multiple codepages support<br />
With ext2fs attributes support<br />
Virtual File Systems:<br />
</p>
<blockquote>
<p>
cpiofs, tarfs, sfs, extfs, ext2undelfs, ftpfs, sftpfs, fish<br />
</p>
</blockquote>
<p>
Data types:<br />
</p>
<blockquote>
<p>
char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;<br />
</p>
</blockquote>
<h2 id="guestOSversion">guest OS version</h2>
<p>
bookworm/sid<br />
</p>
<h2 id="WSL2andhostOSversion">WSL2 and host OS version</h2>
<p>
WSL version: 1.1.6.0<br />
Kernel version: 5.15.90.1<br />
WSLg version: 1.0.50<br />
MSRDC version: 1.2.3770<br />
Direct3D version: 1.608.2-61064218<br />
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp<br />
Windows version: 10.0.22621.1485<br />
</p>
<h2 id="virtualfilesystem">virtual filesystem</h2>
<p>
drvfs on /mnt/d type 9p (rw,noatime,dirsync,aname=drvfs;path=D:\;uid=1000;gid=1000;metadata;umask=22;fmask=11;symlinkroot=/mnt/,mmap,access=client,msize=262144,trans=virtio)<br />
</p>
<h2 id="underlyingfilesystem">underlying filesystem</h2>
<p>
NTFS<br />
</p>
<h2 id="Stepstoreproduce">Steps to reproduce</h2>
<ol><li>install Ubuntu in WSL2 on Windows 11
</li><li>in Ubuntu console run:

```
sudo apt update
sudo apt upgrade
sudo apt install mc
cd /mnt/c/Users/<your windows account name>
mkdir mc_test
for ((i=1; i<=1025; i++ )) ; do touch "`printf %05d $i`" ; done
ls | wc -l  # expected output: 1025
mc
```
</li></ol><h2 id="Expectedoutput">Expected output</h2>
<p>
MC shows all 1025 files<br />
</p>
<h2 id="Actualoutput">Actual output</h2>
<p>
MC shows only files 01023, 01024 and 01025. If you remove these three files, MC shows files 00001 through 1022. <br />
</p>
<h2 id="logs">logs</h2>
<p>
relevant fragment of strace output:<br />
</p>

```
chdir("/mnt/c/users/cezar/mc_test")     = 0
openat(AT_FDCWD, "/mnt/c/users/cezar/mc_test", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 13
newfstatat(13, "", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_EMPTY_PATH) = 0
getdents64(13, 0x562bb8c01630 /* 1024 entries */, 32768) = 32752
lseek(13, 0, SEEK_SET)                  = 0
newfstatat(AT_FDCWD, "/mnt/c/users/cezar", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
getdents64(13, 0x562bb8c01630 /* 3 entries */, 32768) = 96
newfstatat(AT_FDCWD, "/mnt/c/users/cezar/mc_test/01023", {st_mode=S_IFREG|0664, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
newfstatat(AT_FDCWD, "/mnt/c/users/cezar/mc_test/01024", {st_mode=S_IFREG|0664, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
newfstatat(AT_FDCWD, "/mnt/c/users/cezar/mc_test/01025", {st_mode=S_IFREG|0664, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
getdents64(13, 0x562bb8c01630 /* 0 entries */, 32768) = 0
pselect6(6, [5], NULL, NULL, {tv_sec=0, tv_nsec=0}, NULL) = 0 (Timeout)
write(1, "\33[2;136H", 8)               = 8
close(13)                               = 0
```

**Comment by ChieftainY2k** [comment]
Experiencing exactly same problem here (with both Win11 and Win10, newest updates, WSL2) .

Win10/WSL is: 
$ wsl --version
WSL version: 2.6.1.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.66
MSRDC version: 1.2.6353
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.6456

WSL mounts:
```
T:\ on /mnt/t type 9p (rw,noatime,aname=drvfs;path=T:\;uid=1000;gid=1000;symlinkroot=/mnt/,cache=5,access=client,msize=65536,trans=fd,rfd=6,wfd=6)
```

mc does not see first 1022 files when directory contains 1025 files.

<img width="584" height="169" alt="Image" src="https://github.com/user-attachments/assets/f5a3395a-81c8-4bde-88ad-f10ec8ca9a14" />

```
[WSL:ubuntu]test@DESKTOP-GIH9JMS:/mnt/t/tmp/x$ pwd
/mnt/t/tmp/x
[WSL:ubuntu]test@DESKTOP-GIH9JMS:/mnt/t/tmp/x$ find . -maxdepth 1 -type f | wc -l
1025
```

Would be great to have this issue resolved...

**Comment by zyv** [comment]
> Would be great to have this issue resolved...

Well, if you can find out what's going on and suggest a patch that is unproblematic for Unix, we might consider it - it seems that your issue has something to do with Windows-specific implementation problems of the required POSIX interfaces; check related issues #3987 and #4635.

**Comment by ChieftainY2k** [comment]
@zyv Thank you for quick reply. Just wondering, is this issue related (caused by) https://github.com/microsoft/wsl/issues/13613 ?  🤔

**Comment by zyv** [comment]
> [@zyv](https://github.com/zyv) Thank you for quick reply. Just wondering, is this issue related (caused by) [microsoft/WSL#13613](https://github.com/microsoft/WSL/issues/13613) ? 🤔

Sounds very likely.
