### ISSUE TITLE
Misfeature: "history"

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#4529]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4529 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `no` (wfreorrxjeusfcumei@….net) |

<p>
Midnight Commander stores records of user activity in the file <tt>~/.local/share/mc/history</tt>, including directories visited and filenames manipulated.<br />
</p>
<p>
I'm not assuming that anything nefarious is going on, but it's certainly unclear who this file is intended to benefit. I never found a feature of Midnight Commander that allows browsing this "history", and it doesn't appear to be documented. It may be leftover from some uncompleted or abandoned idea. The only references I can find to this file on the web are people trying to find out how to disable it.<br />
</p>
<p>
Personally I am tired of having to remember to disable and delete it on every user account on every system where I install Midnight Commander. This misfeature is best deleted.<br />
</p>
<p>
<strong>At an ABSOLUTE MINIMUM, it must not be enabled by default.</strong><br />
</p>
<p>
This history file in its current form, especially being undocumented and of unclear purpose, is useless, untidy, inappropriate, creepy, and may interfere with data protection legal requirements for some use cases.<br />
</p>

**Comment by Vrihub** [comment]
For the record:

a) You can delete items from the mc internal command history by pressing 'd' or 'delete'; you can delete the whole history by pressing 'D' or 'shift-delete'. This is true for all mc internal history lists (and it seems it's not documented yet. I will open an issue about that)

b) You can disable the mc internal command history by setting `num_history_items_recorded=0` in your `~/.config/mc/ini` file. The command history will be available during the mc session, but it won't be saved to disk.

c) You can prevent mc from writing commands to _your shell's_ history file using a custom shell startup file for mc; e.g. for bash, create the file `~/.local/share/mc/bashrc`:
```
# Optionally include my standard bashrc
# . /home/me/.bashrc
 
# Disable history
set +o history
```
**Edit: see https://github.com/MidnightCommander/mc/issues/4529#issuecomment-3453542001 below for a better solution**

BTW, I did a quick try to implement a new configuration option as an alternative to solution c) above. Rationale: running
`bash -rcfile ~/.bashrc +o history` actually disables history even if it's enabled in `~/.bashrc`.
So I tried to fix the `execl()` call in `subshell/common.c` to:

`execl (mc_global.shell->path, mc_global.shell->path, "-rcfile", init_file, "+o history", (char *) NULL);`

But it doesn't seem to make any difference. Am I missing something?

**Comment by zyv** [comment]
> a) You can delete items from the mc internal command history by pressing 'd' or 'delete'; you can delete the whole history by pressing 'D' or 'shift-delete'. This is true for all mc internal history lists (and it seems it's not documented yet. I will open an issue about that)

Better still, submit a documentation PR directly instead. Thank you.

> `execl (mc_global.shell->path, mc_global.shell->path, "-rcfile", init_file, "+o history", (char *) NULL);`
> 
> But it doesn't seem to make any difference. Am I missing something?

Sorry, no idea.

**Comment by Vrihub** [comment]
> Better still, submit a documentation PR directly instead. Thank you.

Ok, I think I will open a PR to address this (and maybe some of the open issues with the "docs" label) and maybe suggesting some improvements to the docs. Let me know if you have any recommendations and or warnings, I'm not aware of any work currently being done on the docs, maybe I should open a github discussion to coordinate? 

> > `execl (mc_global.shell->path, mc_global.shell->path, "-rcfile", init_file, "+o history", (char *) NULL);`
> > But it doesn't seem to make any difference. Am I missing something?
> 
> Sorry, no idea.

My fault, actually the correct syntax is
`execl (mc_global.shell->path, mc_global.shell->path, "-rcfile", init_file, "+o", "history", (char *) NULL);`
Anyway, this (and the _c)_ solution contained in my previous comment) actually turns off the bash history feature entirely in the mc subshell, i.e. you won't be able to recall previous commands using cursor-up, when in subshell mode.

A better solution is to just unset the bash `HISTFILE` env variable. E.g. in your `~/.local/share/mc/bashrc:`
```
# Optionally include my standard bashrc
# . /home/me/.bashrc
 
# Disable history
export HISTFILE=
```
This disables writing (and reading) your bash history file, but still allows browsing the history of the current mc subshell session with cursor-up/down.

This is equivalent to adding `putenv ((char *) "HISTFILE=");` in the subshell environment setup section of `subshell/common.c`. So a more user-friendly way to disable using the shell history file would be to add a new ini-file setting (`use_shell_history_file`?) that would enable the `putenv` statement above. (All this assumes we're using `bash`, I don't know about other shells)

**Comment by zyv** [comment]
> > Better still, submit a documentation PR directly instead. Thank you.
> 
> Ok, I think I will open a PR to address this (and maybe some of the open issues with the "docs" label) and maybe suggesting some improvements to the docs. Let me know if you have any recommendations and or warnings, I'm not aware of any work currently being done on the docs, maybe I should open a github discussion to coordinate?

Yes, opening a discussion to talk about what you're up to before you invest much effort into that is a very good idea. We might have strong opinions one way or another. And as general (maybe obvious) advice, I would recommend working in self-contained pieces, like for example "document XY", or "update ZZ", instead of "hey, I revamped all your docs, there we go". The latter will take ages to review and adjust, as I wouldn't want to commit something I don't like, but if it's entangled with other good stuff, the good stuff is not going in either...

> This is equivalent to adding `putenv ((char *) "HISTFILE=");` in the subshell environment setup section of `subshell/common.c`. So a more user-friendly way to disable using the shell history file would be to add a new ini-file setting (`use_shell_history_file`?) that would enable the `putenv` statement above. (All this assumes we're using `bash`, I don't know about other shells)

I don't think we ought to do that, and it will be a nightmare to maintain for all the subshells we kind of support. If the user is that paranoid, I can't see why they would want to disable it only for mc, but not globally, so they'd have to put some work into it anyways, and while at it, they can just as well adjust their custom profile for mc however they like.
