### ISSUE TITLE
Add support for bash PROMPT_COMMAND being an array

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#4599]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4599 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `ceamac` (mc@….com) |

<p>
Starting with bash 5.1, PROMPT_COMMAND can be an array.  Detect this<br />
case and append and entry to the array instead of appending to a string.<br />
</p>
<p>
The current behaviour is appending the string to the first element in the array.<br />
</p>
<p>
Testing for bash &gt;= 5 is sufficient, because the @a operator exists in<br />
5.0.  We need eval on the "then" branch because bash 1.x cannot even<br />
parse that line (it does not support arrays).  Tested with bash 1.14.<br />
</p>

> [!NOTE]
> Original attachments:
>
> * [array-PROMPT_COMMAND.patch](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/4599/array-PROMPT_COMMAND.patch) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/4599/array-PROMPT_COMMAND.patch)) by `ceamac` (mc@….com) on <span title="2024-10-13T09:38:50+00:00">`Oct 13, 2024 at 9:38 UTC`</span>

**Comment by egmontkob** [comment]
I know it's always me coming up with this one.....

Noticed that `eval` while cleaning up these init strings and was really wondering why that was there.

>  We need eval on the "then" branch because bash 1.x cannot even parse that line (it does not support arrays). Tested with bash 1.14.

bash 2.0, supporting arrays, was released in 1996.

Do we really need to support almost 30 year old system components?? Why??

Couldn't we please have a little bit cleaner, little bit more trustworthy ("eval is evil" by default) code that just simply breaks if someone pairs up with a component from the previous millennium?

**Comment by zyv** [comment]
> > We need eval on the "then" branch because bash 1.x cannot even parse that line (it does not support arrays). Tested with bash 1.14.
> 
> bash 2.0, supporting arrays, was released in 1996. Do we really need to support almost 30 year old system components?? Why??

This is correct, but `bash` supports arrays specifically for PROMPT_COMMAND only from version 5.1+ released in 2020, which is quite "recent". So I guess the submitter didn’t want to break anything with the code, and given that he still has to support 5.1-, he decided to keep support for 1+ as well.

> Couldn't we please have a little bit cleaner, little bit more trustworthy ("eval is evil" by default) code that just simply breaks if someone pairs up with a component from the previous millennium?

I have no problem removing support for bash 1 if this helps matters, but I would like to keep support for bash 5.1-.

**Comment by egmontkob** [comment]
macOS is stuck on bash 3.2 due to licencing issues, I surely don't want to break that :)

But I'm fairly certain that the "evil eval" hack is no longer needed since bash 2.0. The parser parses everything correctly, and runtime it enters the non-array branch.

**Comment by zyv** [comment]
Feel free to open a separate PR or include it in your other prompt clean-up stuff.

Incidentally, there are some notes on prompt-related matters here - #4634. Unfortunately, I won't be able to get to this anytime soon.

There is also a related issue here, where the submitter disappeared instead of helping to track it down: #4723...
